language: java
jdk:
- oraclejdk8
branches:
  only:
    - master
    - /\d+\.\d+\.\d+/
install:
 ./gradlew shadowJar
deploy:
  provider: releases
  api_key:
    secure: J8P6yUBqsyKfRhsF+EId9qslMNUwOmOjN8d3yeoSZm93khxBHdOh9/t+lxBSNHIHGEWqAlul4vi5xArbZs27v9ajaZDc3U9EdrGqYCw4KshoK51DYMslFR2OSf8xN4RYymvzBeQdMf5RvCQunMPtLgaVrzmL5kKL/F2D+5HMeu3z5tWZew/p37OjCek3fAkkB+RLACl047yp21T6C8zbac4SFybiIVlkbiomtQKqkY8mDfCVGiTkCforAoenNhzjuTw0rUINlPiTo0bLntVvcMjZU2rP9oOsuuGYFaYmz0WrInzAKONA4cN06pS3PN0RB3AxaaIdPTMBpwT2o/hsm4t4bTL9SUwHuWhNK1U2lzxE+9N2An9ww8UyV9Cj2WF5LALLjJJRoaTzax86kbieGIGGujv1k1fTi1BmamrWz5WeqrTjEEZUzqYzV4RJR3avOz2RLcR7o2tUWCwCW7kAW+n+YsII5YSFDJVD9tZW1uXN6V0IAT81AiCTq1QMpmcGAEnXOShOSZydMTAjZvh0/9lPq3y6t01kQHQ51GGfrS4uJ7NTic8NtlfRWL3RfxMOcGxnpHqgNKU2cOFkAXZpOopEpvXskoObBU4Ex0dQkM09oXj37F5/J+D+9UquCOROjKfSqAU8rw8PG4Alap7glvBgKRP8KS8fNUfg3EgJ6cI=
  file: "build/libs/fileRecorder-${TRAVIS_TAG}.jar"
  skip_cleanup: true
  on:
    tags: true
